module.exports = {
  '.txt': 'text/plain',
  '.html': 'text/html',
  '.css': 'text/css',
  '.js': 'application/javascript',
  '.json': 'application/json',
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.pdf': 'application/pdf',
  '.doc': 'application/msword',
  '.docx':
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.xls': 'application/vnd.ms-excel',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.ppt': 'application/vnd.ms-powerpoint',
  '.pptx':
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.csv': 'text/csv',
  '.xml': 'application/xml',
  '.zip': 'application/zip',
  '.tar': 'application/x-tar',
  '.gz': 'application/gzip',
  '.bz2': 'application/x-bzip2',
  '.7z': 'application/x-7z-compressed',
  '.mp3': 'audio/mpeg',
  '.wav': 'audio/wav',
  '.ogg': 'audio/ogg',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.flv': 'video/x-flv',
  '.avi': 'video/x-msvideo',
  '.mov': 'video/quicktime',
  '.mpg': 'video/mpeg',
  '.mpeg': 'video/mpeg',
  '.wmv': 'video/x-ms-wmv',
  '.swf': 'application/x-shockwave-flash',
  '.svg': 'image/svg+xml',
  '.svgz': 'image/svg+xml',
  '.mng': 'video/x-mng',
  '.ico': 'image/x-icon',
  '.woff': 'application/x-font-woff',
  '.woff2': 'application/x-font-woff2',
  '.eot': 'application/vnd.ms-fontobject',
  '.ttf': 'application/x-font-ttf',
  '.otf': 'application/x-font-otf',
  '.ps': 'application/postscript',
  '.xpi': 'application/x-xpinstall',
  '.cab': 'application/vnd.ms-cab-compressed',
  '.exe': 'application/x-msdownload',
  '.msi': 'application/x-msdownload',
  '.crx': 'application/x-chrome-extension',
  '.deb': 'application/vnd.debian.binary-package',
  '.dmg': 'application/x-apple-diskimage',
  '.rpm': 'application/x-rpm',
  '.apk': 'application/vnd.android.package-archive',
  '.jar': 'application/java-archive',
  '.hqx': 'application/mac-binhex40',
  '.torrent': 'application/x-bittorrent',
  '.php': 'application/x-httpd-php',
  '.sql': 'application/x-sql',
};
